[project]
name = "ks-shop-python-sdk"
version = "0.1.2"
description = "Kuaishou Shop Python SDK"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deprecation>=2.1.0",
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
]
